<a href="https://colab.research.google.com/github/pavel-nikitin-2022/ITMO_AI_Python/blob/hw_2/hw_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 2
Author: Pavel Nikitin

## Загрузка датасета

В этом задании используется датасет с информацией о пассажирах Титаника.
Он содержит данные о пассажирах, их классе, возрасте, поле, родственниках на борту и факте выживания.

In [33]:
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Общая информация о датасете

Посмотрим:
- типы данных
- количество строк и столбцов
- количество пропусков
- основные статистические характеристики

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [35]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [36]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Процент выживаемости по классам пассажиров

Pclass:
- 1 — первый класс
- 2 — второй класс
- 3 — третий класс

In [37]:
survival_rate = df.groupby("Pclass")["Survived"].mean() * 100
survival_rate

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

## Самые популярные имена

Из столбца `Name` извлечём собственно имя пассажира и посмотрим самые частые имена среди мужчин и женщин.

In [38]:
import re

def extract_first_name(name):

    # если есть имя в скобках
    match = re.search(r"\((.*?)\)", name)
    if match:
        return match.group(1).split()[0]

    # иначе обычный вариант
    name_part = name.split(",")[1]
    name_part = name_part.split(".")[1]

    return name_part.strip().split()[0]

df["FirstName"] = df["Name"].apply(extract_first_name)

male_name = df[df["Sex"] == "male"]["FirstName"].mode()[0]
female_name = df[df["Sex"] == "female"]["FirstName"].mode()[0]

male_name, female_name

('William', 'Anna')

## Самые популярные мужские и женские имена в каждом классе

Сгруппируем пассажиров по классу (`Pclass`) и полу (`Sex`),
после чего для каждой группы найдём наиболее частое имя (`mode`).

In [39]:
popular_names = (
    df
    .groupby(["Pclass", "Sex"])["FirstName"]
    .agg(lambda x: x.mode()[0])
)

popular_names

Pclass  Sex
1       female    Elizabeth
        male        William
2       female    Elizabeth
        male        William
3       female         Anna
        male        William
Name: FirstName, dtype: object

## Пассажиры старше 44 лет

In [40]:
df[df["Age"] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Elizabeth
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,Mary
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Myna
...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,Peter
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,Margaret
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Sallie
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,Victor
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Lily

## Мужчины младше 44 лет

In [41]:
df[(df["Age"] < 44) & (df["Sex"] == "male")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S,William
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S,Gosta
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S,William
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,Anders
...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,S,Frederick
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S,Henry
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S,Juozas
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C,Karl
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q,Patrick

## Количество n-местных кабин

In [42]:
cabins = df["Cabin"].dropna()

n_places = cabins.apply(lambda x: len(x.split()))

n_places.value_counts()

Cabin
1    180
2     16
3      6
4      2
Name: count, dtype: int64

## Пассажиры без родственников на борту

In [43]:
no_relatives = df[(df["SibSp"] == 0) & (df["Parch"] == 0)]

len(no_relatives)

537