## Домашнее задание 2

- Считайте датасет из файла [train.csv](https://disk.yandex.ru/d/-rPwF6_K4-NIfA) (это данные о выживаемости на Титанике) - **1 балл**
- Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д. - **2 балла**
- Посчитайте процент выживаемости у каждого класса пассажиров (Pclass) - **2 балла**
- Выведите самое популярное мужское и самое популярное женское имя на корабле - **3 балла**
- Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе - **3 балла**
- Выведите часть таблицы с пассажирами, возраст которых больше 44 лет - **2 балла**
- Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола - **3 балла**
- Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека) - **2 балла** 
- Выведите количество пассажиров, у которых нет родственников на борту - **2 балла** 


Для сдачи домашней работы запушьте файлы в ветку **hw_2** в вашем репозитории, создайте pull-request и отправьте на ревью @lyutovad

**Считайте датасет из файла train.csv (это данные о выживаемости на Титанике) - 1 балл**

In [1]:
import pandas as pd

#загрузка файла
df = pd.read_csv('train.csv')

**Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д. - 2 балла**

In [2]:
print("типы данных и пропуски")
print(df.info())

print("\nстатистическое описание")
display(df.describe())

print("\nпропуски по столбцам")
print(df.isnull().sum())

типы данных и пропуски
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

статистическое описание

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

пропуски по столбцам
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Посчитайте процент выживаемости у каждого класса пассажиров (Pclass) - 2 балла

In [3]:
survival_by_class = df.groupby('Pclass')['Survived'].mean() * 100 #здесь мы берем конкретную колонку конкретным признаком и находим среднее
print(survival_by_class)

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

**Выведите самое популярное мужское и самое популярное женское имя на корабле - 3 балла**

In [4]:
def extract_first_name(name):
    #чистим данные столбца от фамилий и mrs.ms.и т.д.
    first_name = name.split(',')[1].split('.')[1].strip()
    #если есть имя в скобках,то берем его
    if '(' in first_name:
        first_name = first_name.split('(')[1].split(' ')[0].replace(')', '')
    else:
        first_name = first_name.split(' ')[0]
    return first_name

#создаем временный столбец с "чистыми" именами
df['FirstName'] = df['Name'].apply(extract_first_name)

#популярные имена в целом, туту мы по столбцу пола берем конкретные мужские и женские 
top_male_name = df[df['Sex'] == 'male']['FirstName'].mode()[0]
top_female_name = df[df['Sex'] == 'female']['FirstName'].mode()[0]

print(f"самое популярное мужское имя: {top_male_name}")
print(f"самое популярное женское имя: {top_female_name}")

самое популярное мужское имя: William
самое популярное женское имя: Anna

**Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе - 3 балла**

In [5]:
#популярные имена в разрезе каждого класса, 
for p_class in sorted(df['Pclass'].unique()):
    m_name = df[(df['Pclass'] == p_class) & (df['Sex'] == 'male')]['FirstName'].mode()[0]
    f_name = df[(df['Pclass'] == p_class) & (df['Sex'] == 'female')]['FirstName'].mode()[0]
    print(f"класс {p_class}: мужское — {m_name}, женское — {f_name}")

класс 1: мужское — William, женское — Elizabeth
класс 2: мужское — William, женское — Elizabeth
класс 3: мужское — William, женское — Anna

**for p_class in sorted(df['Pclass'].unique()):**
находит все уникальные значения в колонке Pclass, сортирует их по порядку и начинает цикл

внутри цикла создаются две выборки:

**df[(df['Pclass'] == p_class) & (df['Sex'] == 'male')]** - только мужчины выбранного класса.

**df[(df['Pclass'] == p_class) & (df['Sex'] == 'female')]** - только женщины выбранного класса.

поиск моды (.mode()[0]):
метод .mode() вычисляет самое часто встречающееся значение в колонке FirstName. Так как мода может вернуть несколько значений, то берется самое первое из них - индекс [0].

----------------------------------

**Выведите часть таблицы с пассажирами, возраст которых больше 44 лет - 2 балла**

**Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола - 3 балла**

In [6]:
#пассажиры старше 44 лет
passengers_over_44 = df[df['Age'] > 44]
print(f"пассажиров старше 44 лет: {len(passengers_over_44)}")

#мужчины младше 44 лет (используем логическое И - &)
young_males = df[(df['Age'] < 44) & (df['Sex'] == 'male')]
print(f"мужчин младше 44 лет: {len(young_males)}")

#выводим первые 5 строк для примера
display(young_males.head())

пассажиров старше 44 лет: 115
мужчин младше 44 лет: 368

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S,William
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S,Gosta
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S,William
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,Anders

**Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека) - **2 балла** **

**Выведите количество пассажиров, у которых нет родственников на борту - **2 балла** **

In [7]:
#считаем n-местные кабины
#сначала считаем, сколько раз встречается номер каждой кабины,dropna убирает пустые значения
#мы смотрим, сколько раз номер каждой конкретной кабины (например, «C23») встречается в списке. 
#если «C23» встречается 3 раза, значит, в ней ехало 3 пассажира.

occupancy = df['Cabin'].dropna().value_counts()

#тут затем считаем частоту этих повторений
#если у нас есть пять разных кабин, в каждой из которых сидело по 2 человека, 
# то для n=2 (двухместные) результат будет count=5

n_place_cabins = occupancy.value_counts().sort_index()

print("Количество кабин с разным числом пассажиров:")
for n, count in n_place_cabins.items():
    print(f"{n}-местных кабин: {count}")

#пассажиры без родственников
#SibSp - братья/сестры/супруги, Parch - родители/дети. Если оба 0 — человек один.
no_fam = df[(df['SibSp'] == 0) & (df['Parch'] == 0)]
print(f"\nКоличество пассажиров без родственников на борту: {len(no_fam)}")

Количество кабин с разным числом пассажиров:
1-местных кабин: 101
2-местных кабин: 38
3-местных кабин: 5
4-местных кабин: 3

Количество пассажиров без родственников на борту: 537

(df['SibSp'] == 0) & (df['Parch'] == 0)

Если оба этих значения равны 0, значит, человек путешествовал без близких родственников, потом код фильтрует таблицу по этим условиям и выводит общее количество таких строк через len()