# Домашнее задание 2
## Анализ датасета Titanic

## Загрузка данных

Считаем датасет Titanic из файла `train.csv` и посмотрим на первые строки таблицы.

In [1]:
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Основная информация о датасете

Выведем:

- структуру данных
- типы столбцов
- количество пропусков
- базовые статистики

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Процент выживаемости по классу пассажиров

Посчитаем процент выживших пассажиров в каждом классе (`Pclass`).

In [5]:
survival_rate = df.groupby("Pclass")["Survived"].mean() * 100
survival_rate

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

Результат показывает, что вероятность выживания зависит от класса пассажира.
Как правило, пассажиры первого класса имели более высокий процент выживания.

## Самые популярные мужские и женские имена

Из столбца `Name` извлечем имя пассажира.

In [6]:
df["FirstName"] = df["Name"].str.extract(r",\s*(?:Mr|Mrs|Miss|Master|Dr)\.\s*([A-Za-z]+)")
df[["Name","FirstName"]].head()

                                                Name FirstName
0                            Braund, Mr. Owen Harris      Owen
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      John
2                             Heikkinen, Miss. Laina     Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Jacques
4                           Allen, Mr. William Henry   William

In [7]:
male_name = df[df["Sex"]=="male"]["FirstName"].value_counts().idxmax()
female_name = df[df["Sex"]=="female"]["FirstName"].value_counts().idxmax()

male_name, female_name

('William', 'William')

Получили наиболее часто встречающиеся мужские и женские имена среди пассажиров.

## Самые популярные имена по полу и классу

In [8]:
for pclass in sorted(df["Pclass"].unique()):

    male = df[(df["Sex"]=="male") & (df["Pclass"]==pclass)]["FirstName"].value_counts().idxmax()

    female = df[(df["Sex"]=="female") & (df["Pclass"]==pclass)]["FirstName"].value_counts().idxmax()

    print(f"Pclass {pclass}:")
    print(" most popular male name:", male)
    print(" most popular female name:", female)
    print()

Pclass 1:
 most popular male name: William
 most popular female name: John

Pclass 2:
 most popular male name: William
 most popular female name: William

Pclass 3:
 most popular male name: William
 most popular female name: Anna

## Пассажиры старше 44 лет

In [9]:
df[df["Age"] > 44].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Elizabeth
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,NaN
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Henry

## Мужчины младше 44 лет

In [10]:
df[(df["Age"] < 44) & (df["Sex"] == "male")].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FirstName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S,William
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S,Gosta
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S,William
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,Anders

## Количество n-местных кают

In [11]:
cabins = df["Cabin"].dropna()

cabin_counts = cabins.str.split().apply(len).value_counts().sort_index()

cabin_counts

Cabin
1    180
2     16
3      6
4      2
Name: count, dtype: int64

Результат показывает количество кают, в которых размещалось 2, 3, 4 и более пассажиров.

## Пассажиры без родственников на борту

In [12]:
no_relatives = df[(df["SibSp"] == 0) & (df["Parch"] == 0)]

len(no_relatives)

537

Мы нашли количество пассажиров, у которых не было родственников на борту.