In [2]:
import pandas as pd

**1 и 2 Пункт**

считывание файла и основная информация

In [6]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

**3 пункт**

Группируем по классу по признаку выжил/нет, вычисляем среднее, далее переводим в проценты, умножая на 100

In [9]:
df.groupby('Pclass')['Survived'].mean()*100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

**4 Пункт**

Признаюсь честно, для выяснения, что из записи является именем, обратился к ИИ. При выполнении задания предполагаю, что первое слово после точки в обращении - имя. Для женщин с двойным именем - первое слово после скобок.

Создадим функцию для извлечения имени.

In [30]:
def get_name (full_name):
  name_p1 = full_name.split(',')[1].strip()
  if '(' in name_p1:
     in_brackets = name_p1.split('(')[1].split(')')[0]
     name = in_brackets.split()[0]
  else:
    after_dot = after_title = name_p1.split('.')[1].strip()
    name = after_title.split()[0]
  return name

теперь с apply применим ф-ю к каждому пассажиру

In [32]:
df['Only_name'] = df['Name'].apply(get_name)
df['Only_name']

0           Owen
1       Florence
2          Laina
3           Lily
4        William
         ...
886       Juozas
887     Margaret
888    Catherine
889         Karl
890      Patrick
Name: Only_name, Length: 891, dtype: object

Теперь найдём самое популярное имя для каждого пола

In [36]:
male_n = df[df['Sex'] == 'male']['Only_name'].value_counts()
popular_m = male_n.index[0]
popular_m
#мужчины

'William'

In [37]:
female_n = df[df['Sex'] == 'female']['Only_name'].value_counts()
popular_fem = female_n.index[0]
popular_fem

'Anna'

**5 Пункт**


Используя столбец only_name из 4 пункта отсортируем по классам и выясним в каждом наиболее популярное имя

In [41]:
male_n_class = df[df['Sex'] == 'male'].groupby('Pclass')['Only_name'].agg(lambda x: x.value_counts().index[0])
female_n_class = df[df['Sex'] == 'female'].groupby('Pclass')['Only_name'].agg(lambda x: x.value_counts().index[0])

male_n_class

Pclass
1    William
2    William
3    William
Name: Only_name, dtype: object

In [42]:
female_n_class

Pclass
1    Elizabeth
2    Elizabeth
3         Anna
Name: Only_name, dtype: object

**6 Пункт**

Для 6 пункта потребуется создать условие и применить по нему фильтр

In [10]:
vozrastnie = df['Age'] > 44 ##создаем условие
otvet1 = df[vozrastnie] #применяем фильтр
otvet1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

**7 Пункт**

Для 7 пункта нужно будет создать два условия и объеденить их

In [12]:
vosrast = df['Age'] > 44 ##создаем условие 1
male = df['Sex'] == 'male' ##создаем условие 2
result = df[(vosrast) & (male)] ##объединяем условия
result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S
...,...,...,...,...,...,...,...,...,...,...,...,...
771,772,0,3,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.0,0,0,PC 17593,79.2000,B82 B84,C
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S

**Пункт 8**

В таблице не указано, сколько мест в кабинах, поэтому потребуется вычислить сколько пассажиров жили вместе, сгруппировать по кабинам, а затем посмотреть размер каждой кабины

In [13]:

pass_w_cab = df[df['Cabin'].notna()] ## уберем пассажиров без кабины

In [15]:
## сгруппируем пассажиров по кабинам, посмотрим размер каждой кабины
cab_size =  pass_w_cab.groupby('Cabin').size()
cab_size

Cabin
A10    1
A14    1
A16    1
A19    1
A20    1
      ..
F33    3
F38    1
F4     2
G6     4
T      1
Length: 147, dtype: int64

In [19]:
## посчитаем сколько кабин какого типа
cab_count = cab_size.value_counts().sort_index()
cab_count

1    101
2     38
3      5
4      3
Name: count, dtype: int64

**Пункт 9**

У пассажира нет родственников, значит выполняется два условия по двум столбцам SibSp = 0 и Parch = 0

In [23]:
no_rel = df[(df['SibSp'] == 0) & (df['Parch'] == 0)]
count_no_rel = len(no_rel)
count_no_rel

537