## Домашнее задание 2

- Считайте датасет из файла [train.csv](https://disk.yandex.ru/d/-rPwF6_K4-NIfA) (это данные о выживаемости на Титанике) - **1 балл**

In [151]:
import pandas as pd

In [152]:
df = pd.read_csv("titanic.csv")

- Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д. - 2 балла

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [154]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

- Посчитайте процент выживаемости у каждого класса пассажиров (Pclass) - **2 балла**

In [155]:
#можно просуммировать, так как 'Survived' принимает значения 1/0
surv_pclass = df.groupby('Pclass').sum('Survived')/df.groupby('Pclass').count() * 100
surv_pclass['Survived']

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

- Выведите самое популярное мужское и самое популярное женское имя на корабле - **3 балла**

In [156]:
#Внимательно изучив данные, увидим, что в признаке Name на самом деле лежит полное имя, поэтому в начале создадим признак Name
df['Full Name'] = df['Name'].copy()
df['Name'] = df['Full Name'].apply(lambda x: x.split(',')[0])
#оставляю только определенный пол и считаю кол-во имен, сортирую по неубыванию
df[df['Sex']=='male']['Name'].value_counts(ascending=False)[:1]

Name
Panula    5
Name: count, dtype: int64

In [157]:
df[df['Sex']=='female']['Name'].value_counts(ascending=False)[:1]

Name
Andersson    6
Name: count, dtype: int64

- Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе - **3 балла**

In [158]:
#повторим операцию, но для каждого класса с использованием группировки
name_sex_pclass = df.groupby(['Pclass', 'Sex', 'Name']).count()

In [159]:
name_sex_pclass.loc[name_sex_pclass.groupby(['Pclass', 'Sex'])['PassengerId'].idxmax()]['PassengerId']

Pclass  Sex     Name
1       female  Allison      2
        male    Carter       2
2       female  Brown        2
        male    Hickman      3
3       female  Andersson    6
        male    Panula       5
Name: PassengerId, dtype: int64

- Выведите часть таблицы с пассажирами, возраст которых больше 44 лет - **2 балла**

In [160]:
df[df['Age']>44].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Full Name
6,7,0,1,McCarthy,male,54.0,0,0,17463,51.8625,E46,S,"McCarthy, Mr. Timothy J"
11,12,1,1,Bonnell,female,58.0,0,0,113783,26.5500,C103,S,"Bonnell, Miss. Elizabeth"
15,16,1,2,Hewlett,female,55.0,0,0,248706,16.0000,NaN,S,"Hewlett, Mrs. (Mary D Kingcome)"
33,34,0,2,Wheadon,male,66.0,0,0,C.A. 24579,10.5000,NaN,S,"Wheadon, Mr. Edward H"
52,53,1,1,Harper,female,49.0,1,0,PC 17572,76.7292,D33,C,"Harper, Mrs. Henry Sleeper (Myna Haxtun)"

- Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола - **3 балла**

In [161]:
df[(df['Age']<44) & (df['Sex'] == 'male')].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Full Name
0,1,0,3,Braund,male,22.0,1,0,A/5 21171,7.250,NaN,S,"Braund, Mr. Owen Harris"
4,5,0,3,Allen,male,35.0,0,0,373450,8.050,NaN,S,"Allen, Mr. William Henry"
7,8,0,3,Palsson,male,2.0,3,1,349909,21.075,NaN,S,"Palsson, Master. Gosta Leonard"
12,13,0,3,Saundercock,male,20.0,0,0,A/5. 2151,8.050,NaN,S,"Saundercock, Mr. William Henry"
13,14,0,3,Andersson,male,39.0,1,5,347082,31.275,NaN,S,"Andersson, Mr. Anders Johan"

- Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека) - **2 балла**

In [162]:
cabins = df.groupby(['Cabin']).size().reset_index(name='n')
cabins['n'].value_counts()[1::]

n
2    38
3     5
4     3
Name: count, dtype: int64

In [163]:
#общее кол-во
(cabins[cabins['n']>1]['Cabin']).count()

np.int64(46)

- Выведите количество пассажиров, у которых нет родственников на борту - **2 балла**

На сайте https://www.kaggle.com/c/titanic/data с датасетом указано следующее

sibsp: The dataset defines family relations in this way...
Sibling = brother, sister, stepbrother, stepsister
Spouse = husband, wife (mistresses and fiancés were ignored)

parch: The dataset defines family relations in this way...
Parent = mother, father
Child = daughter, son, stepdaughter, stepson
Some children travelled only with a nanny, therefore parch=0 for them.

Поэтому ищем пассажиров, у которых нет ни сиблингов ни парентов

In [164]:
df[(df['SibSp']==0) & (df['Parch']==0)]['PassengerId'].count()

np.int64(537)